export const augments = {
  1: { id: 1, name: "마법 가속", rarity: "Prismatic" },
  2: { id: 2, name: "최첨단 발명가", rarity: "Gold" },
  4: { id: 4, name: "기본으로 돌아가기", rarity: "Prismatic" },
  5: { id: 5, name: "지휘관의 깃발", rarity: "Gold" },
  6: { id: 6, name: "검무", rarity: "Prismatic" },
  7: { id: 7, name: "육중한 힘", rarity: "Silver" },
  8: { id: 8, name: "꽉 붙잡아", rarity: "Silver" },
  9: { id: 9, name: "쌍버프", rarity: "Silver" },
  10: { id: 10, name: "포탄", rarity: "Gold" },
  11: { id: 11, name: "난공불락", rarity: "Prismatic" },
  12: { id: 12, name: "위치 변경", rarity: "Silver" },
  13: { id: 13, name: "천상의 신체", rarity: "Gold" },
  14: { id: 14, name: "운전기사", rarity: "Prismatic" },
  15: { id: 15, name: "죽음의 순환", rarity: "Prismatic" },
  16: { id: 16, name: "연계의 대가", rarity: "Gold" },
  17: { id: 17, name: "청부 살인마", rarity: "Silver" },
  18: { id: 18, name: "거석상의 용기", rarity: "Prismatic" },
  19: { id: 19, name: "돌진", rarity: "Prismatic" },
  20: { id: 20, name: "빛의 인도자 결의", rarity: "Gold" },
  21: { id: 21, name: "방어 기동", rarity: "Gold" },
  22: { id: 22, name: "능수능란", rarity: "Silver" },
  23: { id: 23, name: "악마의 춤", rarity: "Gold" },
  24: { id: 24, name: "불사의 날", rarity: "Gold" },
  25: { id: 25, name: "폭격기", rarity: "Gold" },
  26: { id: 26, name: "속전속결", rarity: "Silver" },
  27: { id: 27, name: "대지의 각성", rarity: "Prismatic" },
  28: { id: 28, name: "부식", rarity: "Silver" },
  29: { id: 29, name: "환영 무기", rarity: "Gold" },
  30: { id: 30, name: "유레카", rarity: "Prismatic" },
  31: { id: 31, name: "깨우침", rarity: "Silver" },
  32: { id: 32, name: "처형자", rarity: "Silver" },
  33: { id: 33, name: "늘어나는 팔", rarity: "Gold" },
  34: { id: 34, name: "부패한 방패", rarity: "Silver" },
  35: { id: 35, name: "저주의 화염", rarity: "Prismatic" },
  36: { id: 36, name: "화염 낙인", rarity: "Gold" },
  37: { id: 37, name: "응급처치 키트", rarity: "Silver" },
  38: { id: 38, name: "시작부터 끝까지", rarity: "Gold" },
  39: { id: 39, name: "서리 망령", rarity: "Silver" },
  40: { id: 40, name: "얼어붙은 땅", rarity: "Silver" },
  41: { id: 41, name: "거인", rarity: "Prismatic" },
  42: { id: 42, name: "죄책감의 쾌락", rarity: "Silver" },
  43: { id: 43, name: "불의의 습격", rarity: "Silver" },
  44: { id: 44, name: "차가운 냉기", rarity: "Silver" },
  45: { id: 45, name: "지옥의 전도체", rarity: "Prismatic" },
  46: { id: 46, name: "지옥불 영혼", rarity: "Silver" },
  47: { id: 47, name: "치명적인 공격", rarity: "Gold" },
  48: { id: 48, name: "보석 건틀릿", rarity: "Prismatic" },
  49: { id: 49, name: "주스 팩", rarity: "Silver" },
  50: { id: 50, name: "핵심 룬 요술사", rarity: "Gold" },
  51: { id: 51, name: "불을 밝혀", rarity: "Silver" },
  52: { id: 52, name: "벼락", rarity: "Gold" },
  53: { id: 53, name: "미친 과학자", rarity: "Prismatic" },
  54: { id: 54, name: "결투의 대가", rarity: "Prismatic" },
  55: { id: 55, name: "야간 급행", rarity: "Silver" },
  56: { id: 56, name: "정신 변환", rarity: "Silver" },
  57: { id: 57, name: "대지의 영혼", rarity: "Silver" },
  58: { id: 58, name: "신비한 주먹", rarity: "Prismatic" },
  59: { id: 59, name: "신화", rarity: "Gold" },
  60: { id: 60, name: "바다의 영혼", rarity: "Silver" },
  61: { id: 61, name: "부메랑 투척", rarity: "Gold" },
  62: { id: 62, name: "전능의 영혼", rarity: "Prismatic" },
  63: { id: 63, name: "무법자의 투지", rarity: "Gold" },
  64: { id: 64, name: "인내심", rarity: "Gold" },
  65: { id: 65, name: "극악무도", rarity: "Gold" },
  66: { id: 66, name: "양자 연산", rarity: "Prismatic" },
  67: { id: 67, name: "선동", rarity: "Gold" },
  68: { id: 68, name: "되풀이", rarity: "Gold" },
  69: { id: 69, name: "반발", rarity: "Silver" },
  70: { id: 70, name: "끊임없는 회복", rarity: "Gold" },
  71: { id: 71, name: "상급 조준경 부착", rarity: "Gold" },
  72: { id: 72, name: "타오르는 새벽", rarity: "Gold" },
  73: { id: 73, name: "그림자 질주", rarity: "Silver" },
  74: { id: 74, name: "감쇠 광선", rarity: "Gold" },
  75: { id: 75, name: "찜솥", rarity: "Prismatic" },
  76: { id: 76, name: "음속 폭발", rarity: "Silver" },
  77: { id: 77, name: "영혼 흡수", rarity: "Gold" },
  78: { id: 78, name: "정신 결속", rarity: "Prismatic" },
  79: { id: 79, name: "전장의 교향곡", rarity: "Prismatic" },
  80: { id: 80, name: "확률적 방어", rarity: "Silver" },
  81: { id: 81, name: "탭 댄서", rarity: "Prismatic" },
  82: { id: 82, name: "야수화", rarity: "Gold" },
  83: { id: 83, name: "도적의 장갑", rarity: "Prismatic" },
  84: { id: 84, name: "바늘에 실 끼우기", rarity: "Gold" },
  85: { id: 85, name: "고문자", rarity: "Silver" },
  86: { id: 86, name: "정조준 일격 신동", rarity: "Prismatic" },
  87: { id: 87, name: "태풍", rarity: "Silver" },
  88: { id: 88, name: "궁극기 대변혁", rarity: "Prismatic" },
  89: { id: 89, name: "소멸", rarity: "Gold" },
  90: { id: 90, name: "복수", rarity: "Gold" },
  91: { id: 91, name: "선순환", rarity: "Silver" },
  92: { id: 92, name: "취약", rarity: "Silver" },
  93: { id: 93, name: "준비 운동", rarity: "Silver" },
  94: { id: 94, name: "희생의 의지", rarity: "Gold" },
  95: { id: 95, name: "바람전달자의 축복", rarity: "Prismatic" },
  96: { id: 96, name: "세월의 지혜", rarity: "Prismatic" },
  97: { id: 97, name: "사악한 정신", rarity: "Silver" },
  98: { id: 98, name: "속행", rarity: "Gold" },
  99: { id: 99, name: "존야의 강림", rarity: "Prismatic" },
  102: { id: 102, name: "따라올 테면 따라와 봐", rarity: "Silver" },
  103: { id: 103, name: "빵과 버터", rarity: "Gold" },
  104: { id: 104, name: "소환술사", rarity: "Gold" },
  105: { id: 105, name: "민병대", rarity: "Silver" },
  107: { id: 107, name: "두 배 세 배", rarity: "Gold" },
  108: { id: 108, name: "자폭", rarity: "Silver" },
  109: { id: 109, name: "계약", rarity: "Gold" },
  110: { id: 110, name: "빨랫줄", rarity: "Silver" },
  112: { id: 112, name: "궁극의 저지 불가", rarity: "Silver" },
  113: { id: 113, name: "노련한 저격수", rarity: "Gold" },
  115: { id: 115, name: "최상급 조준경 부착", rarity: "Prismatic" },
  116: { id: 116, name: "점멸 난사", rarity: "Silver" },
  118: { id: 118, name: "치명적 치유", rarity: "Gold" },
  120: { id: 120, name: "기사회생", rarity: "Silver" },
  123: { id: 123, name: "소환사의 룰렛", rarity: "Prismatic" },
  125: { id: 125, name: "끝판왕", rarity: "Prismatic" },
  129: { id: 129, name: "마법 명사수", rarity: "Gold" },
  133: { id: 133, name: "마법 미사일", rarity: "Gold" },
  134: { id: 134, name: "검을 뽑아라", rarity: "Prismatic" },
  135: { id: 135, name: "주문 각성", rarity: "Prismatic" },
  136: { id: 136, name: "우당탕탕", rarity: "Silver" },
  138: { id: 138, name: "선혈포식", rarity: "Silver" },
  141: { id: 141, name: "너만을 위해", rarity: "Gold" },
  149: { id: 149, name: "넘을 수 없는 벽", rarity: "Gold" },
  150: { id: 150, name: "빵과 잼", rarity: "Gold" },
  151: { id: 151, name: "빵과 치즈", rarity: "Gold" },
  152: { id: 152, name: "퀘스트: 강철 같은 심장", rarity: "Gold" },
  154: { id: 154, name: "퀘스트: 우르프의 챔피언", rarity: "Gold" },
  156: { id: 156, name: "퀘스트: 우글렛의 마녀 모자", rarity: "Prismatic" },
  165: { id: 165, name: "재시작", rarity: "Gold" },
  166: { id: 166, name: "연쇄 번개", rarity: "Prismatic" },
  170: { id: 170, name: "조준경 부착", rarity: "Silver" },
  171: { id: 171, name: "해체분석", rarity: "Silver" },
  172: { id: 172, name: "거울 환영", rarity: "Silver" },
  174: { id: 174, name: "눈알 광선", rarity: "Prismatic" },
  175: { id: 175, name: "기생 관계", rarity: "Gold" },
  176: { id: 176, name: "눈싸움!", rarity: "Silver" },
  177: { id: 177, name: "마트료시카", rarity: "Prismatic" },
  180: { id: 180, name: "전술적 대비", rarity: "Gold" },
  181: { id: 181, name: "강타자", rarity: "Silver" },
  187: { id: 187, name: "점멸탄", rarity: "Silver" },
  192: { id: 192, name: "퀘스트: 응징의 천사", rarity: "Gold" },
  193: { id: 193, name: "우주의 중심", rarity: "Prismatic" },
  194: { id: 194, name: "요정 마법", rarity: "Prismatic" },
  195: { id: 195, name: "거인 학살자", rarity: "Prismatic" },
  198: { id: 198, name: "신성한 불길", rarity: "Gold" },
  200: { id: 200, name: "피를 나눈 형제", rarity: "Gold" },
  204: { id: 204, name: "다단 중첩", rarity: "Silver" },
  205: { id: 205, name: "적응형 능력치", rarity: "Silver" },
  206: { id: 206, name: "마법사 (물리)", rarity: "Silver" },
  207: { id: 207, name: "미동 없이", rarity: "Silver" },
  208: { id: 208, name: "궤도형 레이저", rarity: "Prismatic" },
  210: { id: 210, name: "암습", rarity: "Gold" },
  211: { id: 211, name: "처형 시간", rarity: "Gold" },
  213: { id: 213, name: "완전 자동화", rarity: "Silver" },
  214: { id: 214, name: "승리를 위한 회전", rarity: "Silver" },
  215: { id: 215, name: "어둠의 축복", rarity: "Gold" },
  216: { id: 216, name: "역병술사", rarity: "Prismatic" },
  217: { id: 217, name: "죽음의 손길", rarity: "Gold" },
  218: { id: 218, name: "신성 모독자", rarity: "Silver" },
  219: { id: 219, name: "파멸의 예언자", rarity: "Prismatic" },
  220: { id: 220, name: "감바 모루", rarity: "Prismatic" },
};
